name: Part 2 - C#

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/csharp_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/csharp_solution/**'
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      working-directory: './part_2/csharp_solution'
      run: dotnet publish --configuration Release
    - name: test
      working-directory: './part_2/csharp_solution'
      run: dotnet test --configuration Release
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: part_2_csharp	
        path: |
          ./part_2/csharp_solution/Exchange/bin/Release/net10.0/publish/* 
          ./part_2/csharp_solution/runner
        overwrite: true